query BoardsList ($customFilter: BoardFilter) {
    boardsList(filter: $customFilter) {
        items {
            id
            title
            image {
                downloadUrl
            }
        }
    }
}
